### ISSUE TITLE
Test rules don't actually run without __main__ clause

### ISSUE THREAD

**Issue by danielhfrank** [nettle/bazel-python-unittest#3]
Hello! Just an FYI, the test targets in this repo aren't actually run when running e.g. `bazel test :test_one`. Try raising an exception in the test to see for yourself. To make them run, one needs to add:
```
if __name__ == "__main__":
    unittest.main()
```
to each `test_*` file. The `run_tests` rule works just fine without that, since it has its own entry point.

**Comment by nettle** [comment]
You are right! Thanks for noticing!
